def sum_even_odd(numbers):
    """
    Calculate the sum of even and odd numbers in a list.

    Args:
        numbers (list[int]): A list of integers.

    Returns:
        tuple: A tuple (even_sum, odd_sum) where
            even_sum is the total of all even numbers,
            odd_sum is the total of all odd numbers.
    """
    even_sum = 0
    odd_sum = 0

    for n in numbers:
        if n % 2 == 0:
            even_sum += n
        else:
            odd_sum += n

    return even_sum, odd_sum
#  This is the docstring generated by copilot
"""
Returns the sum of even and odd values from a list.

Args:
    numbers (list): A list containing integer values.

Returns:
    tuple: A pair where the first element is the sum of even integers
    and the second element is the sum of odd integers.
"""
